export const style = {
  wrapper: `w-screen flex items-center justify-center mt-14 font-mono`,
  content: `bg-[#EDF1F7] w-[40rem] rounded-xl p-4 appearance-none shadow-xl`,
  formHeader: `px-2 flex items-center justify-between font-semibold text-xl text-blue-600`,
  transferPropContainer: `bg-[#fff] my-3 rounded-2xl p-6 text-3xl  border border-[#D4DBE5] hover:border-[#6CA6F6]  flex justify-between appearance-none text-blue-600`,
  transferPropInput: `bg-transparent placeholder:text-[#B2B9D2] outline-none mb-6 w-full text-2xl`,
  currencySelector: `flex w-1/4`,
  currencySelectorContent: `w-full h-min flex justify-between items-center bg-[#EDF1F7] hover:bg-[#CFD9E7] rounded-2xl text-xl font-medium cursor-pointer p-2 mt-[-0.2rem]`,
  currencySelectorIcon: `flex items-center`,
  currencySelectorTicker: `mx-2 text-[#B2B9D2]`,
  currencySelectorArrow: `text-lg text-[#B2B9D2]`,
  confirmButton: `bg-[#6CA6F6] my-2 rounded-2xl py-6 px-8 text-xl text-white font-semibold flex items-center justify-center cursor-pointer border hover:bg-blue-500`,
  ulStyles: `list-disc list-inside pl-2 marker:text-[#6CA6F6]`,
  liStyles: `text-lg text-[#B2B9D2]`,
};
